### ISSUE TITLE
Is it possible to use an output from a another profile?

### ISSUE THREAD

**Issue by gugaiz** [scalefactory/tfctl#17]
Sorry to rise an issue about that but didn't know where to ask. 

Is it possible to use the output of a module implementation in a profile (like [this one](https://github.com/scalefactory/tfctl/blob/master/examples/control_tower/profiles/example-profile/main.tf#L1) supposing it has some outputs) into another profile definition?

Thanks

**Comment by word** [comment]
Unfortunately it's currently no possible to pass outputs between profiles.

You can sometimes use data sources to get data about resources managed in one profile into another.  

Another option is to write data into something like the SSM parameter store in one profile and read it back in another (as a data source):

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_parameter
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ssm_parameter

One thing to keep in mind is that it isn't currently possible to define dependencies between profiles which can make those approaches troublesome.  With terraform 0.13 and support for modules `depends_on`, this could be added fairly easily though.

**Comment by gugaiz** [comment]
Hi @word, thanks for the answer. Could you give an idea on how you use profiles on the real scenario? 
I am trying to figure out how to use them but I am not too sure yet. Possible scenarios are:

- One profile per account (dev, staging, prod) and inside that profile defining modules/resources for that env. I think that is a bit pointless because I will have to redefine almost the same configurations across the different accounts but I will be able to get the outputs from a vpc module to use them on the creation of the other resources.
- Using one profile per major resource definition (vpc, beanstalk, s3), I think this could work considering that variables for the different envs can be set at the `tfctl.yaml` but if I can't get the vpc_id from the vpc profile on the beanstalk profile, it is not possible to use it.
- One central profile to create all resources (a lot of files inside) on the different accounts based on values defined on `tfctl.yaml`, but I guess this could be hard to maintain mainly handing a lot of exceptions about the creation of certain resources across the different accounts. 

How do you normally use those profiles across the multiple accounts?
Thanks

**Comment by word** [comment]
I usually create profiles that contains all related resources and try to avoid dependencies between profiles.  Profiles are usually composed out of Terraform modules and those modules define the individual resources.  This way Terraform can workout the dependency graph for you.

If you are deploying similar configuration to multiple accounts you can define a single profile and declare it at an OU or organization level rather than individual accounts.  You can vary the configuration per account if you like.  A simple example could look like this:

```
organization_units:
  workload: 
    data: 
      common: 'some common config'
    profiles:
      - application-stack-x

account_overrides:
  test:
    data:
      vpc_cidr: '10.10.0.0/16'
      environment_name: 'test'
      multi_az: false
  staging:
    data:
      vpc_cidr: '10.11.0.0/16'
      environment_name: 'staging'
      multi_az: true
   production:
    data:
      vpc_cidr: '10.12.0.0/16'
      environment_name: 'production'
      multi_az: true
```

The example assumes you have a `workload` OU in your organisation which contains 3 accounts: test, staging and production.  You can assign the `application-stack-x` to all accounts under the workload OU along with any common (or default) configuration data.  You can also define account specific configuration under each account.  In the above example I set the `test` account to be a single az deployment but staging and production are multi az.  The `application-stack-x`profile can access this data through the `config` variable and can make decisions based on where it's running and how those parameters are set.
